name: CraftZ
main: de.minestar.craftz.Core
version: ${pom.version}
commands:
    game:
        description: CraftZ-Related commands
        usage: /game <cmd 1> ... <cmd n>
    ready:
        description: SurvivalGames-Related commands
        usage: /ready